name: Autoprovision Exoscale

on:
  push:
    branches: [ "autoprovision-exoscale" ]
    paths:
      - 'cluster-autoscaler/**'
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    name: Build and push container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker metadata (tags, labels)
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: registry.flux.host/cluster-autoscaler

      - name: Generate Flux Host JWT
        id: jwt
        uses: ./.github/actions/generate-jwt
        with:
          api-key: ${{ secrets.FLUX_HOST_API_KEY }}

      - name: Log in to Flux Host Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.flux.host
          username: ${{ steps.jwt.outputs.userId }}
          password: ${{ steps.jwt.outputs.token }}

      - name: Build and push image to flux-host registry
        uses: docker/build-push-action@v5
        with:
          context: ./cluster-autoscaler
          file: ./cluster-autoscaler/Dockerfile
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
